//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ozet
    {
        public int OzetId { get; set; }
        public Nullable<int> OzetIslemNumarasi { get; set; }
        public Nullable<bool> OzetIade { get; set; }
        public string OzetOdemeSekli { get; set; }
        public Nullable<double> OzetNakit { get; set; }
        public Nullable<double> OzetKart { get; set; }
        public Nullable<bool> OzetGelir { get; set; }
        public Nullable<bool> OzetGider { get; set; }
        public Nullable<double> OzetFiyatToplam { get; set; }
        public string OzetAciklama { get; set; }
        public Nullable<System.DateTime> OzetTarih { get; set; }
        public string OzetKullanici { get; set; }
    }
}
