//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satiss
    {
        public int satisId { get; set; }
        public Nullable<int> islemNumarasi { get; set; }
        public string urunAdi { get; set; }
        public string urunBarkodu { get; set; }
        public string urunGrubu { get; set; }
        public string urunBirim { get; set; }
        public Nullable<double> alisFiyati { get; set; }
        public Nullable<double> satisFiyati { get; set; }
        public Nullable<double> miktari { get; set; }
        public Nullable<double> toplami { get; set; }
        public Nullable<double> kdvTutar { get; set; }
        public string odemeSekli { get; set; }
        public Nullable<bool> iadeIslem { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public string kullaniciAdi { get; set; }
    }
}
